export const commonPhrases = {
  en: {
    name: 'English',
    phrases: [
      { text: 'Hello, how are you?', category: 'Greetings' },
      { text: 'Nice to meet you', category: 'Greetings' },
      { text: 'Good morning', category: 'Greetings' },
      { text: 'Good evening', category: 'Greetings' },
      { text: 'Thank you very much', category: 'Polite' },
      { text: 'You\'re welcome', category: 'Polite' },
      { text: 'Please', category: 'Polite' },
      { text: 'Excuse me', category: 'Polite' },
      { text: 'Where is the bathroom?', category: 'Travel' },
      { text: 'How much does this cost?', category: 'Shopping' },
      { text: 'I don\'t understand', category: 'Communication' },
      { text: 'Can you help me?', category: 'Emergency' },
      { text: 'I need a doctor', category: 'Emergency' },
      { text: 'What is your name?', category: 'Conversation' },
      { text: 'My name is...', category: 'Conversation' },
    ]
  },
  es: {
    name: 'Spanish',
    phrases: [
      { text: 'Hola, ¿cómo estás?', category: 'Greetings' },
      { text: 'Mucho gusto', category: 'Greetings' },
      { text: 'Buenos días', category: 'Greetings' },
      { text: 'Buenas noches', category: 'Greetings' },
      { text: 'Muchas gracias', category: 'Polite' },
      { text: 'De nada', category: 'Polite' },
      { text: 'Por favor', category: 'Polite' },
      { text: 'Disculpe', category: 'Polite' },
      { text: '¿Dónde está el baño?', category: 'Travel' },
      { text: '¿Cuánto cuesta esto?', category: 'Shopping' },
      { text: 'No entiendo', category: 'Communication' },
      { text: '¿Puede ayudarme?', category: 'Emergency' },
      { text: 'Necesito un médico', category: 'Emergency' },
      { text: '¿Cómo te llamas?', category: 'Conversation' },
      { text: 'Me llamo...', category: 'Conversation' },
    ]
  },
  fr: {
    name: 'French',
    phrases: [
      { text: 'Bonjour, comment allez-vous?', category: 'Greetings' },
      { text: 'Enchanté', category: 'Greetings' },
      { text: 'Bonjour', category: 'Greetings' },
      { text: 'Bonsoir', category: 'Greetings' },
      { text: 'Merci beaucoup', category: 'Polite' },
      { text: 'De rien', category: 'Polite' },
      { text: 'S\'il vous plaît', category: 'Polite' },
      { text: 'Excusez-moi', category: 'Polite' },
      { text: 'Où sont les toilettes?', category: 'Travel' },
      { text: 'Combien ça coûte?', category: 'Shopping' },
      { text: 'Je ne comprends pas', category: 'Communication' },
      { text: 'Pouvez-vous m\'aider?', category: 'Emergency' },
      { text: 'J\'ai besoin d\'un médecin', category: 'Emergency' },
      { text: 'Comment vous appelez-vous?', category: 'Conversation' },
      { text: 'Je m\'appelle...', category: 'Conversation' },
    ]
  },
  de: {
    name: 'German',
    phrases: [
      { text: 'Hallo, wie geht es Ihnen?', category: 'Greetings' },
      { text: 'Freut mich', category: 'Greetings' },
      { text: 'Guten Morgen', category: 'Greetings' },
      { text: 'Guten Abend', category: 'Greetings' },
      { text: 'Vielen Dank', category: 'Polite' },
      { text: 'Bitte schön', category: 'Polite' },
      { text: 'Bitte', category: 'Polite' },
      { text: 'Entschuldigung', category: 'Polite' },
      { text: 'Wo ist die Toilette?', category: 'Travel' },
      { text: 'Wie viel kostet das?', category: 'Shopping' },
      { text: 'Ich verstehe nicht', category: 'Communication' },
      { text: 'Können Sie mir helfen?', category: 'Emergency' },
      { text: 'Ich brauche einen Arzt', category: 'Emergency' },
      { text: 'Wie heißen Sie?', category: 'Conversation' },
      { text: 'Ich heiße...', category: 'Conversation' },
    ]
  },
  it: {
    name: 'Italian',
    phrases: [
      { text: 'Ciao, come stai?', category: 'Greetings' },
      { text: 'Piacere', category: 'Greetings' },
      { text: 'Buongiorno', category: 'Greetings' },
      { text: 'Buonasera', category: 'Greetings' },
      { text: 'Grazie mille', category: 'Polite' },
      { text: 'Prego', category: 'Polite' },
      { text: 'Per favore', category: 'Polite' },
      { text: 'Scusi', category: 'Polite' },
      { text: 'Dov\'è il bagno?', category: 'Travel' },
      { text: 'Quanto costa questo?', category: 'Shopping' },
      { text: 'Non capisco', category: 'Communication' },
      { text: 'Può aiutarmi?', category: 'Emergency' },
      { text: 'Ho bisogno di un medico', category: 'Emergency' },
      { text: 'Come ti chiami?', category: 'Conversation' },
      { text: 'Mi chiamo...', category: 'Conversation' },
    ]
  },
  pt: {
    name: 'Portuguese',
    phrases: [
      { text: 'Olá, como você está?', category: 'Greetings' },
      { text: 'Prazer em conhecê-lo', category: 'Greetings' },
      { text: 'Bom dia', category: 'Greetings' },
      { text: 'Boa noite', category: 'Greetings' },
      { text: 'Muito obrigado', category: 'Polite' },
      { text: 'De nada', category: 'Polite' },
      { text: 'Por favor', category: 'Polite' },
      { text: 'Com licença', category: 'Polite' },
      { text: 'Onde fica o banheiro?', category: 'Travel' },
      { text: 'Quanto custa isto?', category: 'Shopping' },
      { text: 'Eu não entendo', category: 'Communication' },
      { text: 'Pode me ajudar?', category: 'Emergency' },
      { text: 'Preciso de um médico', category: 'Emergency' },
      { text: 'Qual é o seu nome?', category: 'Conversation' },
      { text: 'Meu nome é...', category: 'Conversation' },
    ]
  },
  ja: {
    name: 'Japanese',
    phrases: [
      { text: 'こんにちは、お元気ですか？', category: 'Greetings' },
      { text: 'はじめまして', category: 'Greetings' },
      { text: 'おはようございます', category: 'Greetings' },
      { text: 'こんばんは', category: 'Greetings' },
      { text: 'どうもありがとうございます', category: 'Polite' },
      { text: 'どういたしまして', category: 'Polite' },
      { text: 'お願いします', category: 'Polite' },
      { text: 'すみません', category: 'Polite' },
      { text: 'トイレはどこですか？', category: 'Travel' },
      { text: 'これはいくらですか？', category: 'Shopping' },
      { text: '分かりません', category: 'Communication' },
      { text: '手伝ってくれますか？', category: 'Emergency' },
      { text: '医者を呼んでください', category: 'Emergency' },
      { text: 'お名前は何ですか？', category: 'Conversation' },
      { text: '私の名前は...', category: 'Conversation' },
    ]
  },
  ko: {
    name: 'Korean',
    phrases: [
      { text: '안녕하세요, 어떻게 지내세요?', category: 'Greetings' },
      { text: '만나서 반갑습니다', category: 'Greetings' },
      { text: '좋은 아침이에요', category: 'Greetings' },
      { text: '좋은 저녁이에요', category: 'Greetings' },
      { text: '정말 감사합니다', category: 'Polite' },
      { text: '천만에요', category: 'Polite' },
      { text: '부탁드립니다', category: 'Polite' },
      { text: '실례합니다', category: 'Polite' },
      { text: '화장실이 어디에 있나요?', category: 'Travel' },
      { text: '이거 얼마예요?', category: 'Shopping' },
      { text: '이해가 안 돼요', category: 'Communication' },
      { text: '도와주실 수 있나요?', category: 'Emergency' },
      { text: '의사를 불러주세요', category: 'Emergency' },
      { text: '이름이 뭐예요?', category: 'Conversation' },
      { text: '제 이름은...', category: 'Conversation' },
    ]
  },
  zh: {
    name: 'Chinese',
    phrases: [
      { text: '你好，你好吗？', category: 'Greetings' },
      { text: '很高兴认识你', category: 'Greetings' },
      { text: '早上好', category: 'Greetings' },
      { text: '晚上好', category: 'Greetings' },
      { text: '非常感谢', category: 'Polite' },
      { text: '不客气', category: 'Polite' },
      { text: '请', category: 'Polite' },
      { text: '不好意思', category: 'Polite' },
      { text: '洗手间在哪里？', category: 'Travel' },
      { text: '这个多少钱？', category: 'Shopping' },
      { text: '我不明白', category: 'Communication' },
      { text: '你能帮我吗？', category: 'Emergency' },
      { text: '我需要看医生', category: 'Emergency' },
      { text: '你叫什么名字？', category: 'Conversation' },
      { text: '我叫...', category: 'Conversation' },
    ]
  },
  ar: {
    name: 'Arabic',
    phrases: [
      { text: 'مرحبا، كيف حالك؟', category: 'Greetings' },
      { text: 'سررت بلقائك', category: 'Greetings' },
      { text: 'صباح الخير', category: 'Greetings' },
      { text: 'مساء الخير', category: 'Greetings' },
      { text: 'شكرا جزيلا', category: 'Polite' },
      { text: 'على الرحب والسعة', category: 'Polite' },
      { text: 'من فضلك', category: 'Polite' },
      { text: 'عذرا', category: 'Polite' },
      { text: 'أين الحمام؟', category: 'Travel' },
      { text: 'كم سعر هذا؟', category: 'Shopping' },
      { text: 'لا أفهم', category: 'Communication' },
      { text: 'هل يمكنك مساعدتي؟', category: 'Emergency' },
      { text: 'أحتاج طبيب', category: 'Emergency' },
      { text: 'ما اسمك؟', category: 'Conversation' },
      { text: 'اسمي...', category: 'Conversation' },
    ]
  },
  hi: {
    name: 'Hindi',
    phrases: [
      { text: 'नमस्ते, आप कैसे हैं?', category: 'Greetings' },
      { text: 'आपसे मिलकर खुशी हुई', category: 'Greetings' },
      { text: 'सुप्रभात', category: 'Greetings' },
      { text: 'शुभ संध्या', category: 'Greetings' },
      { text: 'बहुत धन्यवाद', category: 'Polite' },
      { text: 'आपका स्वागत है', category: 'Polite' },
      { text: 'कृपया', category: 'Polite' },
      { text: 'माफ़ कीजिये', category: 'Polite' },
      { text: 'शौचालय कहाँ है?', category: 'Travel' },
      { text: 'यह कितने का है?', category: 'Shopping' },
      { text: 'मुझे समझ नहीं आ रहा', category: 'Communication' },
      { text: 'क्या आप मेरी मदद कर सकते हैं?', category: 'Emergency' },
      { text: 'मुझे डॉक्टर चाहिए', category: 'Emergency' },
      { text: 'आपका नाम क्या है?', category: 'Conversation' },
      { text: 'मेरा नाम... है', category: 'Conversation' },
    ]
  },
  ru: {
    name: 'Russian',
    phrases: [
      { text: 'Привет, как дела?', category: 'Greetings' },
      { text: 'Приятно познакомиться', category: 'Greetings' },
      { text: 'Доброе утро', category: 'Greetings' },
      { text: 'Добрый вечер', category: 'Greetings' },
      { text: 'Большое спасибо', category: 'Polite' },
      { text: 'Пожалуйста', category: 'Polite' },
      { text: 'Пожалуйста', category: 'Polite' },
      { text: 'Извините', category: 'Polite' },
      { text: 'Где туалет?', category: 'Travel' },
      { text: 'Сколько это стоит?', category: 'Shopping' },
      { text: 'Я не понимаю', category: 'Communication' },
      { text: 'Можете мне помочь?', category: 'Emergency' },
      { text: 'Мне нужен врач', category: 'Emergency' },
      { text: 'Как вас зовут?', category: 'Conversation' },
      { text: 'Меня зовут...', category: 'Conversation' },
    ]
  },
}

export const categories = [
  'Greetings',
  'Polite',
  'Travel',
  'Shopping',
  'Communication',
  'Emergency',
  'Conversation',
]

export const getPhrasesByLanguage = (langCode: string) => {
  return commonPhrases[langCode as keyof typeof commonPhrases] || commonPhrases.en
}

export const getPhrasesByCategory = (langCode: string, category: string) => {
  const phrases = getPhrasesByLanguage(langCode)
  return phrases.phrases.filter(p => p.category === category)
}
